In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
import pandas as pd

In [2]:
df  = pd.read_csv(r'C:\Users\DELL\Downloads\titanic.csv', delimiter = ',')

In [3]:
df.head()

Pclass                                            Name     Sex   Age  \
0       2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1       3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2       2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3       3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4       3                          Sutehall, Mr. Henry Jr    male  25.0   

   SibSp  Parch           Ticket    Fare Cabin Embarked  Survived  
0      1      0           228414  26.000   NaN        S         1  
1      0      0         A/5 2466   8.050   NaN        S         0  
2      0      0           250655  26.000   NaN        S         0  
3      0      4           349909  21.075   NaN        S         0  
4      0      0  SOTON/OQ 392076   7.050   NaN        S         0

In [4]:
df.drop('Name',axis = 1,inplace = True)


In [5]:
df.head()

Pclass     Sex   Age  SibSp  Parch           Ticket    Fare Cabin Embarked  \
0       2  female  29.0      1      0           228414  26.000   NaN        S   
1       3    male   NaN      0      0         A/5 2466   8.050   NaN        S   
2       2    male  39.0      0      0           250655  26.000   NaN        S   
3       3  female  29.0      0      4           349909  21.075   NaN        S   
4       3    male  25.0      0      0  SOTON/OQ 392076   7.050   NaN        S   

   Survived  
0         1  
1         0  
2         0  
3         0  
4         0

In [6]:
del df["Cabin"]

In [7]:
df.head()

Pclass     Sex   Age  SibSp  Parch           Ticket    Fare Embarked  \
0       2  female  29.0      1      0           228414  26.000        S   
1       3    male   NaN      0      0         A/5 2466   8.050        S   
2       2    male  39.0      0      0           250655  26.000        S   
3       3  female  29.0      0      4           349909  21.075        S   
4       3    male  25.0      0      0  SOTON/OQ 392076   7.050        S   

   Survived  
0         1  
1         0  
2         0  
3         0  
4         0

In [8]:
df.isnull().sum()

Pclass        0
Sex           0
Age         132
SibSp         0
Parch         0
Ticket        0
Fare          0
Embarked      1
Survived      0
dtype: int64

In [9]:
del df["Age"]

In [10]:
df.head()


Pclass     Sex  SibSp  Parch           Ticket    Fare Embarked  Survived
0       2  female      1      0           228414  26.000        S         1
1       3    male      0      0         A/5 2466   8.050        S         0
2       2    male      0      0           250655  26.000        S         0
3       3  female      0      4           349909  21.075        S         0
4       3    male      0      0  SOTON/OQ 392076   7.050        S         0

In [11]:
df.dropna(inplace = True)
df.reset_index(drop = True,inplace = True)

In [12]:
del df["Ticket"]

In [13]:
def f(string):
    if (string == "male"):
        return 0
    else:
        return 1

df["Sex"] = df.Sex.apply(f)




In [14]:
df.head()

Pclass  Sex  SibSp  Parch    Fare Embarked  Survived
0       2    1      1      0  26.000        S         1
1       3    0      0      0   8.050        S         0
2       2    0      0      0  26.000        S         0
3       3    1      0      4  21.075        S         0
4       3    0      0      0   7.050        S         0

In [15]:
alg1 = LogisticRegression()

In [16]:
def a(s):
    if(s == 'S'):
        return 0
    if(s == 'C'):
        return 1
    if(s == 'Q'):
        return 2

df["Embarked"] = df.Embarked.apply(a)
df.head()

Pclass  Sex  SibSp  Parch    Fare  Embarked  Survived
0       2    1      1      0  26.000         0         1
1       3    0      0      0   8.050         0         0
2       2    0      0      0  26.000         0         0
3       3    1      0      4  21.075         0         0
4       3    0      0      0   7.050         0         0

In [17]:
df.tail()

Pclass  Sex  SibSp  Parch     Fare  Embarked  Survived
662       2    1      0      0  10.5000         0         1
663       3    0      0      0   7.7500         2         0
664       3    0      0      0  56.4958         0         1
665       3    1      0      0   9.8375         0         0
666       3    1      1      0  15.5000         2         1

In [18]:
titanic_ds = df.to_numpy()

In [19]:
titanic_ds

array([[ 2.    ,  1.    ,  1.    , ..., 26.    ,  0.    ,  1.    ],
       [ 3.    ,  0.    ,  0.    , ...,  8.05  ,  0.    ,  0.    ],
       [ 2.    ,  0.    ,  0.    , ..., 26.    ,  0.    ,  0.    ],
       ...,
       [ 3.    ,  0.    ,  0.    , ..., 56.4958,  0.    ,  1.    ],
       [ 3.    ,  1.    ,  0.    , ...,  9.8375,  0.    ,  0.    ],
       [ 3.    ,  1.    ,  1.    , ..., 15.5   ,  2.    ,  1.    ]])

In [20]:
X = titanic_ds[:,:-1]
Y = titanic_ds[:,-1]

In [21]:
Y

array([1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1.,
       0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1.,
       1., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1.,
       0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0.,
       1., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 0.

In [22]:
df1 = pd.read_csv(r'C:\Users\DELL\Downloads\titanic1.csv',delimiter = ',')

In [23]:
df1.head()

Pclass                                               Name     Sex   Age  \
0       2                     Davies, Master. John Morgan Jr    male   8.0   
1       1                        Leader, Dr. Alice (Farnham)  female  49.0   
2       3                            Kilgannon, Mr. Thomas J    male   NaN   
3       2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0   
4       1                          McGough, Mr. James Robert    male  36.0   

   SibSp  Parch      Ticket     Fare Cabin Embarked  
0      1      1  C.A. 33112  36.7500   NaN        S  
1      0      0       17465  25.9292   D17        S  
2      0      0       36865   7.7375   NaN        Q  
3      2      1      243847  27.0000   NaN        S  
4      0      0    PC 17473  26.2875   E25        S

In [24]:
del df1["Name"]
del df1["Cabin"]
df.head()

Pclass  Sex  SibSp  Parch    Fare  Embarked  Survived
0       2    1      1      0  26.000         0         1
1       3    0      0      0   8.050         0         0
2       2    0      0      0  26.000         0         0
3       3    1      0      4  21.075         0         0
4       3    0      0      0   7.050         0         0

In [25]:
df1.head()

Pclass     Sex   Age  SibSp  Parch      Ticket     Fare Embarked
0       2    male   8.0      1      1  C.A. 33112  36.7500        S
1       1  female  49.0      0      0       17465  25.9292        S
2       3    male   NaN      0      0       36865   7.7375        Q
3       2  female  24.0      2      1      243847  27.0000        S
4       1    male  36.0      0      0    PC 17473  26.2875        S

In [26]:
del df1["Age"]
del df1["Ticket"]

In [27]:
df1.head()

Pclass     Sex  SibSp  Parch     Fare Embarked
0       2    male      1      1  36.7500        S
1       1  female      0      0  25.9292        S
2       3    male      0      0   7.7375        Q
3       2  female      2      1  27.0000        S
4       1    male      0      0  26.2875        S

In [28]:
def c(s):
    if(s == "male"):
        return 0
    else:
        return 1

def d(z):
    if(z == 'S'):
        return 0
    if(z == 'C'):
        return 1
    if(z == 'Q'):
        return 2

df1["Sex"] = df1.Sex.apply(c)
df1["Embarked"] = df1.Embarked.apply(d)

df1.head()
    

Pclass  Sex  SibSp  Parch     Fare  Embarked
0       2    0      1      1  36.7500       0.0
1       1    1      0      0  25.9292       0.0
2       3    0      0      0   7.7375       2.0
3       2    1      2      1  27.0000       0.0
4       1    0      0      0  26.2875       0.0

In [29]:
alg1.fit(X,Y)

LogisticRegression()

In [30]:
alg1.score(X,Y)

0.7856071964017991

In [31]:
df1.isnull().sum()

Pclass      0
Sex         0
SibSp       0
Parch       0
Fare        0
Embarked    1
dtype: int64

In [32]:
df1.dropna(inplace = True)
df1.reset_index(drop = True,inplace = True)

In [33]:
df1.isnull().sum()

Pclass      0
Sex         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [34]:
df1.index

RangeIndex(start=0, stop=222, step=1)

In [35]:
X_test = df1.to_numpy()

In [36]:
Y_predict = alg1.predict(X_test)

In [37]:
Y_predict

array([0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0.,
       0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 1.,
       1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1.,
       0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0.,
       0.])

In [38]:
np.savetxt("titanic_predict.csv",Y_predict,delimiter = ',',fmt = "%0.1f")